// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/44449d5481a1bec25d9f61bfee04722bb7f8ccaf/file-type/index.d.ts
declare module 'file-type' {
// Type definitions for file-type
// Project: https://github.com/sindresorhus/file-type
// Definitions by: KIM Jaesuck a.k.a. gim tcaesvk <http://github.com/tcaesvk/>
// Definitions: https://github.com/DefinitelyType/DefinitelyTyped

/// <reference types="node" />

export = FileType;

function FileType(buf: Buffer): FileType.FileTypeResult;

namespace FileType {
    export interface FileTypeResult {
        ext: string;
        mime: string;
    }
}
}
